// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI agent to provide tip suggestions based on customer feedback.
 *
 * - suggestTip - A function that handles the tip suggestion process.
 * - SuggestTipInput - The input type for the suggestTip function.
 * - SuggestTipOutput - The return type for the suggestTip function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestTipInputSchema = z.object({
  customerFeedback: z
    .string()
    .describe('The feedback provided by the customer about their experience.'),
  orderDetails: z.string().describe('Details about the customer order, including items and total amount.'),
  paymentInfo: z.string().describe('Information about the payment method used.'),
});
export type SuggestTipInput = z.infer<typeof SuggestTipInputSchema>;

const SuggestTipOutputSchema = z.object({
  suggestedTipPercentage: z
    .number()
    .describe('The suggested tip percentage based on the customer feedback and order details.'),
  suggestedTipAmount: z
    .number()
    .describe('The suggested tip amount in the local currency.'),
  reasoning: z
    .string()
    .describe('The reasoning behind the suggested tip amount, based on the provided inputs.'),
});
export type SuggestTipOutput = z.infer<typeof SuggestTipOutputSchema>;

export async function suggestTip(input: SuggestTipInput): Promise<SuggestTipOutput> {
  return suggestTipFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestTipPrompt',
  input: {schema: SuggestTipInputSchema},
  output: {schema: SuggestTipOutputSchema},
  prompt: `You are an AI assistant designed to suggest appropriate tip amounts for restaurant bills.

Analyze the customer feedback, order details, and payment information to determine a suitable tip percentage and amount.

Consider factors such as customer satisfaction, order complexity, and payment method.

Customer Feedback: {{{customerFeedback}}}
Order Details: {{{orderDetails}}}
Payment Info: {{{paymentInfo}}}

Based on this information, provide a suggested tip percentage, a suggested tip amount, and a clear reasoning for your suggestion.

Output the suggested tip percentage, suggested tip amount, and reasoning in a JSON format.
`,
});

const suggestTipFlow = ai.defineFlow(
  {
    name: 'suggestTipFlow',
    inputSchema: SuggestTipInputSchema,
    outputSchema: SuggestTipOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
